version: '3'

networks:
  camunda_network:
    driver: bridge

services:
  dpe-camunda:
    image: dpe/dpe-camunda-microservice-demo:0.1.0-SNAPSHOT
    container_name: dpe_camunda_demo
    networks:
      - camunda_network
    ports:
      - 8080:8080
      - 9999:9999
    volumes:
      - ./config:/config
    environment:
      JAVA_OPTS: >-
        -Xms128M -Xmx256M
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Djava.rmi.server.hostname=127.0.0.1
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
