version: '3'

services:
  camunda:
    image: dpe/camunda-microservice-web-rest:latest
    container_name: camunda_microservice_web_rest
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M

  db:
    image: mysql:latest
    container_name: camunda_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=camunda_db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=camunda
    volumes:
      - ./camunda_mysql:/var/lib/mysql

