version: '3'

networks:
  camunda_network:
    driver: bridge
    
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: camunda_rabbitmq
    networks:
      - camunda_network
    ports:
      - 5672:5672
      - 15671:15671
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

