version: '3'

networks:
  camunda_network:
    driver: bridge

services:
  camunda-web-rest-undertow:
    image: dpe/camunda-microservice-web-rest-undertow:0.1.0-SNAPSHOT
    container_name: camunda_web_rest_undertow
    networks:
      - camunda_network
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M

