version: '3'

networks:
  camunda_network:
    driver: bridge
    
services:
  db:
    image: mysql:5.7
    container_name: camunda_mysql
    networks:
      - camunda_network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=camunda_db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=camunda
    volumes:
      - ./camunda_mysql:/var/lib/mysql

