info:
  app: 
    name: Camunda Microservice Web
    description: Minimalised Camunda BPM Web Console for Microservice
    maintainer: Alex Park <alexspark@deloitte.com.au>

camunda.bpm:
  enabled: true
  filter:
    create: All tasks    
  database:
    type: mysql
    
camunda.bpm.management:
  health.camunda.enabled: true

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/camunda_db?autoReconnect=true
  
management.endpoints.web.exposure: 
  include: '*'
  