camunda:
  bpm:
    id-generator: simple  
    
spring.datasource:
  url: jdbc:h2:mem:camunda
#  url: jdbc:h2:jdbc:h2:./camunda-h2-dbs/process-engine;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
