info:
  app: 
    name: DPE Camunda BPM Web & Rest Starter - local
    description: DPE Camunda BPM Web and Rest API Spring Boot Starter
#    maintainer: Alex Park <alexspark@deloitte.com.au>
    env: local

camunda.bpm:
  filter:
    create: All tasks    
  database:
    type: h2

spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
    
demo:
  enabled: true
  remoteAddress: 127.0.0.1
  security:
    username: admin-local
    roles:
      - USER
      - ADMIN
  